# Generated by Django 5.1.1 on 2024-09-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_usereraylearning_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereraylearning',
            name='study_level',
            field=models.CharField(blank=True, choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], max_length=3, null=True),
        ),
    ]
