# Generated by Django 5.1.1 on 2024-09-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_usereraylearning_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereraylearning',
            name='matricule',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
