# Generated by Django 5.1.1 on 2024-09-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_usereraylearning_study_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereraylearning',
            name='matricule',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
