# Generated by Django 5.1.1 on 2024-09-23 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_usereraylearning_matricule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usereraylearning',
            name='address',
        ),
        migrations.RemoveField(
            model_name='usereraylearning',
            name='date_of_birth',
        ),
    ]
