# Generated by Django 5.1.1 on 2024-09-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_usereraylearning_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereraylearning',
            name='matricule',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
