# Generated by Django 5.1.1 on 2024-09-23 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_usereraylearning_matricule'),
        ('courses', '0006_alter_cours_level_alter_student_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereraylearning',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.filiere'),
        ),
    ]
