# Generated by Django 5.1.1 on 2024-09-23 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_cours_level_student_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='matricule',
        ),
    ]
