# Generated by Django 5.1.1 on 2024-09-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_note_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiere',
            name='date',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
